/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpRouteImport } from './routes/help'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DataIntegrationRouteImport } from './routes/data.integration'
import { Route as DataMasterRouteImport } from './routes/data.master'
import { Route as PlanningSmartdemandRouteImport } from './routes/planning.smartdemand'
import { Route as PlanningWhatIfRouteImport } from './routes/planning.what-if'
import { Route as ProcurementIntelligenceRouteImport } from './routes/procurement.intelligence'
import { Route as ProcurementWhatIfRouteImport } from './routes/procurement.what-if'
import { Route as ReportingFeedbackRouteImport } from './routes/reporting.feedback'
import { Route as ReportingForecastExportRouteImport } from './routes/reporting.forecast-export'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIntegrationRoute = DataIntegrationRouteImport.update({
  id: '/data/integration',
  path: '/data/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const DataMasterRoute = DataMasterRouteImport.update({
  id: '/data/master',
  path: '/data/master',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningSmartdemandRoute = PlanningSmartdemandRouteImport.update({
  id: '/planning/smartdemand',
  path: '/planning/smartdemand',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningWhatIfRoute = PlanningWhatIfRouteImport.update({
  id: '/planning/what-if',
  path: '/planning/what-if',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementIntelligenceRoute = ProcurementIntelligenceRouteImport.update({
  id: '/procurement/intelligence',
  path: '/procurement/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementWhatIfRoute = ProcurementWhatIfRouteImport.update({
  id: '/procurement/what-if',
  path: '/procurement/what-if',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingFeedbackRoute = ReportingFeedbackRouteImport.update({
  id: '/reporting/feedback',
  path: '/reporting/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingForecastExportRoute = ReportingForecastExportRouteImport.update({
  id: '/reporting/forecast-export',
  path: '/reporting/forecast-export',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/settings': typeof SettingsRoute
  '/data/integration': typeof DataIntegrationRoute
  '/data/master': typeof DataMasterRoute
  '/planning/smartdemand': typeof PlanningSmartdemandRoute
  '/planning/what-if': typeof PlanningWhatIfRoute
  '/procurement/intelligence': typeof ProcurementIntelligenceRoute
  '/procurement/what-if': typeof ProcurementWhatIfRoute
  '/reporting/feedback': typeof ReportingFeedbackRoute
  '/reporting/forecast-export': typeof ReportingForecastExportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/settings': typeof SettingsRoute
  '/data/integration': typeof DataIntegrationRoute
  '/data/master': typeof DataMasterRoute
  '/planning/smartdemand': typeof PlanningSmartdemandRoute
  '/planning/what-if': typeof PlanningWhatIfRoute
  '/procurement/intelligence': typeof ProcurementIntelligenceRoute
  '/procurement/what-if': typeof ProcurementWhatIfRoute
  '/reporting/feedback': typeof ReportingFeedbackRoute
  '/reporting/forecast-export': typeof ReportingForecastExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/settings': typeof SettingsRoute
  '/data/integration': typeof DataIntegrationRoute
  '/data/master': typeof DataMasterRoute
  '/planning/smartdemand': typeof PlanningSmartdemandRoute
  '/planning/what-if': typeof PlanningWhatIfRoute
  '/procurement/intelligence': typeof ProcurementIntelligenceRoute
  '/procurement/what-if': typeof ProcurementWhatIfRoute
  '/reporting/feedback': typeof ReportingFeedbackRoute
  '/reporting/forecast-export': typeof ReportingForecastExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/settings'
    | '/data/integration'
    | '/data/master'
    | '/planning/smartdemand'
    | '/planning/what-if'
    | '/procurement/intelligence'
    | '/procurement/what-if'
    | '/reporting/feedback'
    | '/reporting/forecast-export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/settings'
    | '/data/integration'
    | '/data/master'
    | '/planning/smartdemand'
    | '/planning/what-if'
    | '/procurement/intelligence'
    | '/procurement/what-if'
    | '/reporting/feedback'
    | '/reporting/forecast-export'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/settings'
    | '/data/integration'
    | '/data/master'
    | '/planning/smartdemand'
    | '/planning/what-if'
    | '/procurement/intelligence'
    | '/procurement/what-if'
    | '/reporting/feedback'
    | '/reporting/forecast-export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRoute: typeof HelpRoute
  SettingsRoute: typeof SettingsRoute
  DataIntegrationRoute: typeof DataIntegrationRoute
  DataMasterRoute: typeof DataMasterRoute
  PlanningSmartdemandRoute: typeof PlanningSmartdemandRoute
  PlanningWhatIfRoute: typeof PlanningWhatIfRoute
  ProcurementIntelligenceRoute: typeof ProcurementIntelligenceRoute
  ProcurementWhatIfRoute: typeof ProcurementWhatIfRoute
  ReportingFeedbackRoute: typeof ReportingFeedbackRoute
  ReportingForecastExportRoute: typeof ReportingForecastExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/integration': {
      id: '/data/integration'
      path: '/data/integration'
      fullPath: '/data/integration'
      preLoaderRoute: typeof DataIntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/master': {
      id: '/data/master'
      path: '/data/master'
      fullPath: '/data/master'
      preLoaderRoute: typeof DataMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning/smartdemand': {
      id: '/planning/smartdemand'
      path: '/planning/smartdemand'
      fullPath: '/planning/smartdemand'
      preLoaderRoute: typeof PlanningSmartdemandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning/what-if': {
      id: '/planning/what-if'
      path: '/planning/what-if'
      fullPath: '/planning/what-if'
      preLoaderRoute: typeof PlanningWhatIfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/intelligence': {
      id: '/procurement/intelligence'
      path: '/procurement/intelligence'
      fullPath: '/procurement/intelligence'
      preLoaderRoute: typeof ProcurementIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/what-if': {
      id: '/procurement/what-if'
      path: '/procurement/what-if'
      fullPath: '/procurement/what-if'
      preLoaderRoute: typeof ProcurementWhatIfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/feedback': {
      id: '/reporting/feedback'
      path: '/reporting/feedback'
      fullPath: '/reporting/feedback'
      preLoaderRoute: typeof ReportingFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/forecast-export': {
      id: '/reporting/forecast-export'
      path: '/reporting/forecast-export'
      fullPath: '/reporting/forecast-export'
      preLoaderRoute: typeof ReportingForecastExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRoute: HelpRoute,
  SettingsRoute: SettingsRoute,
  DataIntegrationRoute: DataIntegrationRoute,
  DataMasterRoute: DataMasterRoute,
  PlanningSmartdemandRoute: PlanningSmartdemandRoute,
  PlanningWhatIfRoute: PlanningWhatIfRoute,
  ProcurementIntelligenceRoute: ProcurementIntelligenceRoute,
  ProcurementWhatIfRoute: ProcurementWhatIfRoute,
  ReportingFeedbackRoute: ReportingFeedbackRoute,
  ReportingForecastExportRoute: ReportingForecastExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
